services:
  postgres:
    image: postgres:16-alpine
    container_name: pdks-postgres
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: pdks
      POSTGRES_USER: pdks
      POSTGRES_PASSWORD: pdks123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
